### ISSUE TITLE
subtract_imagenet_mean_batch is not working

### ISSUE THREAD

**Issue by underfitting** [zhanghang1989/PyTorch-Style-Transfer#1]
Hi,

I think the function utils.subtract_imagenet_mean_batch does not work with current code.
You need to add "return batch" in the function and

`utils.subtract_imagenet_mean_batch(xc)`

should be changed to

`xc = utils.subtract_imagenet_mean_batch(xc)`

**Comment by zhanghang1989** [comment]
Hi, thanks for pointing out the mistake! it is fixed in recent commit. 👍
