### ISSUE TITLE
Temporal coherence?

### ISSUE THREAD

**Issue by rraallvv** [zhanghang1989/PyTorch-Style-Transfer#10]
Have you tried some technique for temporal coherence? If not, would you mind if I ask which one would you recommend or would like to try.

Keep up the good work.

**Comment by zhanghang1989** [comment]
What do you mean by 'temporal coherence'? Thx

**Comment by rraallvv** [comment]
@zhanghang1989 sorry, I should have been more clear regarding what I meant for temporal coherence. Normally when neural style transfer is applied to each individual frame in a video, the output seems to have some artifacts that appear randomly, so they try add some coherence between consecutive frames. [Here](https://www.youtube.com/watch?v=Uxax5EKg0zA) is a video with some examples. By the way, the results on images I've obtained using your code are awesome!

**Comment by zhanghang1989** [comment]
Thanks @rraallvv  for clarify 'temporal coherence'! I am glad that you enjoy the code. 
Sorry that I don't have much experience of video style transfer. Good luck to your work!
