### ISSUE TITLE
optim with normal RAM?

### ISSUE THREAD

**Issue by pingu2k4** [zhanghang1989/PyTorch-Style-Transfer#6]
Hi,

So I spent around 24 hours so far training a model on my style images, got the results out by using the model on eval and so far they're not great. When I use the optim function with the styles however the results are pretty decent, however I am limited by my VRAM which is 6GB as to what size images I can output. Having a lot more RAM available, I was hoping I could do pretty decently sized images, but it seems that I can only get much larger images with eval. Does eval use normal RAM instead of VRAM? 

I will continue training my model so that I can use eval in the future, whether I can do larger images with optim or not, but no idea how much more training is required to make it anywhere near a respectable result.

What sort of overall loss value should I be aiming for? Does the number of style images make a difference to what I should expect?

**Comment by zhanghang1989** [comment]
It's hard to say the expected loss value, but ideally the model should approximate Gaty's approach pretty well.
